### PR TITLE
Sc108934/add shiftleft scan 

### PR DESCRIPTION
**Pull request by PeterHuang516**

### CODE REVIEW

**Review by neo-anand-patel — APPROVED** [review]
dunno why build is failing but looks good otherwise

**Review by AdamTranquilla — COMMENTED** [review]
have you added the secrets for this? They might be available at an org level already

**Comment by AdamTranquilla** [comment]
That check should pass before we merge this

**Comment by PeterHuang516** [comment]
> have you added the secrets for this? They might be available at an org level already

I'm using the org level secrets

**Review by AD-Blue — APPROVED** [review]

**Review by ryanliew-neo — APPROVED** [review]

**Review by AdamTranquilla — APPROVED** [review]

**Pull request merged**
